spring:
  datasource:
    url: jdbc:mysql://123.56.229.155:3306/mydemo?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc123456a.
  redis:
    host: 123.56.229.155
    port: 6379
    timeout: 10000
server:
  port: 8081

logging:
  pattern:
    level: debug
  file:
    path: C:\Users\Administrator\Desktop\mySpringBoot/springdemo.log

