#  mybatis 配置
spring:
  datasource:
    url: jdbc:mysql://123.56.229.155:3306/mydemo?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Abc123456a.
  redis:
    host: 123.56.229.155
    port: 6379
    timeout: 10000
    password: Abc123456a.
    lettuce:
      pool:
        max-active: 200
        max-idle: 8
        min-idle: 0


#mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.mydemo.demo.modules.*.entity
  mapper-locations: classpath:mapper/*/*.xml
  global-config:
    db-config:
      logic-delete-value: 1

#   线上
#    spring:
#      datasource:
#        url: jdbc:mysql://127.0.0.1:3306/mydemo?useUnicode=true&characterEncoding=utf8
#        driverClassName: com.mysql.cj.jdbc.Driver
#        username: root
#        password: Abc123456a.
#      redis:
#        host: 127.0.0.1
#        port: 6379
#        timeout: 10000
#        password: Abc123456a.

server:
  port: 8089

logging:
  pattern:
    level: debug
  file:
    path: C:\Users\Administrator\Desktop\mySpringBoot/springdemo.log

